In [14]:
import pandas as pd
import numpy as np


In [15]:
df=pd.read_csv("C:\\Users\\yasha\\OneDrive\\Desktop\ML\\iris.csv")

In [16]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
Species={"Species":{'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}}
df=df.replace(Species)
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [32]:
X=df.drop('Species',axis=1)
y=df['Species']

In [33]:
print('Shape of X= ',X.shape)
print('Shape of y= ',y.shape)

Shape of X=  (150, 5)
Shape of y=  (150,)


In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=51)
print('Shape of X_train= ',X_train.shape)
print('Shape of X_test= ',X_test.shape)
print('Shape of y_train= ',y_train.shape)
print('Shape of y_test= ',y_test.shape)


Shape of X_train=  (120, 5)
Shape of X_test=  (30, 5)
Shape of y_train=  (120,)
Shape of y_test=  (30,)


In [40]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(criterion='mse')
regressor.fit(X_train,y_train)


C:\Users\yasha\anaconda3\lib\site-packages\sklearn\tree\_classes.py:359: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warnings.warn(


DecisionTreeRegressor(criterion='mse')

In [41]:
regressor.score(X_test,y_test)

0.956140350877193

In [48]:
y_pred=regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_pred.reshape(len(y_test),1)),1))

[[1. 1.]
 [2. 2.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [0. 0.]
 [2. 2.]
 [2. 2.]
 [0. 0.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [1. 1.]
 [2. 2.]
 [1. 1.]
 [2. 2.]
 [0. 0.]
 [2. 2.]
 [2. 2.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [2. 2.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [2. 2.]]


In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,pred)
print(cm)

[[ 9  0  0]
 [ 0  6  0]
 [ 0  1 14]]
